### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by eisbehr-** [colinmollenhour/credis#118]
Hello,

your `credis` is used by Magento 2. When i try to use `redis` there, i get the following error:

> Fatal error: Uncaught CredisException: Connection to Redis 127.0.0.1:6379 failed after 2 failures.Last Error : (13) Permission denied in /var/www/html/magento/vendor/colinmollenhour/credis/Client.php:475 Stack trace: #0 /var/www/html/magento/vendor/colinmollenhour/credis/Client.php(471): Credis_Client->connect() #1 /var/www/html/magento/vendor/colinmollenhour/credis/Client.php(784): Credis_Client->connect() #2 /var/www/html/magento/vendor/colinmollenhour/credis/Client.php(637): Credis_Client->__call('select', Array) #3 /var/www/html/magento/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(393): Credis_Client->select(1) #4 /var/www/html/magento/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(250): Cm_Cache_Backend_Redis->_applyClientOptions(Object(Credis_Client)) #5 /var/www/html/magento/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct(Array) #6 /var/www/html/magento/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache: in /var/www/html/magento/vendor/colinmollenhour/credis/Client.php on line 475

What makes me curious is the "persmission". Do you know what kind of permission is requested there? I don't use a password on my `redis` and on `cli` it works fine too. For example:

```SHELL
$ redis-cli -h 127.0.0.1 -p 6379 -a '' -n 2
```

If this helps in any way, this is my current config:

```PHP
'cache' => [
        'frontend' => [
            'default' => [
                'id_prefix' => '0mc_',
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => '127.0.0.1',
                    'database' => '0',
                    'port' => '6379',
                    'password' => ''
                ]
            ],
            'page_cache' => [
                'id_prefix' => '1pc_',
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => '127.0.0.1',
                    'database' => '1',
                    'port' => '6379',
                    'compress_data' => '0',
                    'password' => ''
                ]
            ]
        ]
    ],
```

Maybe you can guide me in the right direction. ;)
Thanks

**Comment by eisbehr-** [comment]
I've found the issue. It was caused by my apache. Using `sudo setsebool httpd_can_network_connect on` fixed the issue. But it's interesing that there will be a _permission_ error thrown and no _connection_ error?! Anyway, currently solved for me. ;)
